name: gnn_edge_embedding
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.10.1
  - networkx=3.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  - pyyaml=6.0.1
  - colorama=0.4.6
  - pip
  - pip:
    - torch-geometric==2.4.0
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-cluster==1.6.3
    - torch-spline-conv==1.2.2
    - plotly==5.8.0 